import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { buildPrTitle, buildPrBody } from '../lib/pr-body.js';

describe('buildPrTitle', () => {
  it('returns the first line of the task, trimmed', () => {
    assert.equal(
      buildPrTitle('  Add publish phase\n\nwith more detail below'),
      'Add publish phase',
    );
  });

  it('leaves titles of 72 characters or fewer untouched', () => {
    const exact = 'x'.repeat(72);
    assert.equal(buildPrTitle(exact), exact);
    assert.equal(buildPrTitle('short title'), 'short title');
  });

  it('truncates past 72 chars at the last word boundary and appends …', () => {
    // 80 chars of words; truncation must land on a space and keep the result ≤72.
    const long =
      'Implement a careful publish phase that pushes the branch and opens a PR via gh';
    assert.ok(long.length > 72);
    const title = buildPrTitle(long);
    assert.ok(title.endsWith('…'), `expected ellipsis suffix, got: ${title}`);
    assert.ok(title.length <= 72, `expected ≤72 chars, got ${title.length}: ${title}`);
    assert.doesNotMatch(title.slice(0, -1), /\s$/, 'should not leave a trailing space before …');
    const withoutEllipsis = title.slice(0, -1);
    assert.ok(
      long.startsWith(withoutEllipsis),
      `truncated title without … should be a prefix of the task; got: ${title}`,
    );
  });

  it('does not add an orch: prefix', () => {
    assert.equal(buildPrTitle('fix the typo'), 'fix the typo');
    assert.doesNotMatch(buildPrTitle('fix the typo'), /^orch:/);
  });
});

describe('buildPrBody', () => {
  const changes = {
    files: [
      { status: 'M', path: 'main.js' },
      { status: 'A', path: 'lib/publish.js' },
    ],
    shortstat: '2 files changed, 118 insertions(+), 3 deletions(-)',
  };

  it('includes the full task text, files-changed block, and orch footer', () => {
    const body = buildPrBody({
      task: 'Add publish (--pr)\n\nPush and open a PR.',
      plan: '- [ ] wire flags\n- [ ] call gh',
      changes,
      slug: 'brave-kestrel-0ad0',
      agent: 'claude',
      version: '1.4.0',
    });

    assert.match(body, /^Add publish \(--pr\)\n\nPush and open a PR\./);
    assert.match(body, /## Plan\n\n- \[ \] wire flags\n- \[ \] call gh/);
    assert.match(body, /## Files changed\n\n```text\n {2}M {2}main\.js\n {2}A {2}lib\/publish\.js\n {2}2 files changed, 118 insertions\(\+\), 3 deletions\(-\)\n```/);
    assert.match(
      body,
      /Generated by orch 1\.4\.0 · run `brave-kestrel-0ad0` · agent `claude`/,
    );
  });

  it('omits the Plan section when plan is missing, null, or only whitespace', () => {
    for (const plan of [undefined, null, '', '   \n\t  ']) {
      const body = buildPrBody({
        task: 'Add publish',
        plan,
        changes,
        slug: 'slug-slug-0000',
        agent: 'cursor',
        version: '1.4.0',
      });
      assert.doesNotMatch(body, /## Plan/, `plan=${JSON.stringify(plan)} should omit Plan`);
      assert.match(body, /## Files changed/);
    }
  });

  it('renders status letters, paths, and shortstat from collectWorktreeChanges shape', () => {
    const body = buildPrBody({
      task: 'task',
      plan: 'plan text',
      changes: {
        files: [
          { status: 'A', path: 'test/pr-body.test.js' },
          { status: 'M', path: 'lib/commit.js' },
        ],
        shortstat: '2 files changed, 40 insertions(+), 3 deletions(-)',
      },
      slug: 'stub-stub-0000',
      agent: 'claude',
      version: '1.4.0',
    });

    assert.match(body, / {2}A {2}test\/pr-body\.test\.js/);
    assert.match(body, / {2}M {2}lib\/commit\.js/);
    assert.match(body, / {2}2 files changed, 40 insertions\(\+\), 3 deletions\(-\)/);
  });

  it('footer carries slug, agent, and version', () => {
    const body = buildPrBody({
      task: 'task',
      plan: 'plan',
      changes,
      slug: 'calm-otter-7f3a',
      agent: 'agn',
      version: '2.0.0',
    });
    assert.match(body, /Generated by orch 2\.0\.0 · run `calm-otter-7f3a` · agent `agn`/);
  });
});
