/**
 * Pure PR title/body formatting for the publish phase. No I/O — callers pass
 * in task text, plan contents, and the collectWorktreeChanges rollup.
 */

/**
 * First line of the task, trimmed. Past 72 chars: truncate at the last word
 * boundary that fits and append `…`. No `orch:` prefix.
 *
 * @param {string} task
 * @returns {string}
 */
export function buildPrTitle(task) {
    const firstLine = String(task ?? '').split('\n')[0].trim();
    if (firstLine.length <= 72) return firstLine;

    const budget = 71; // room for the single-char ellipsis
    let truncated = firstLine.slice(0, budget);
    const lastSpace = truncated.lastIndexOf(' ');
    if (lastSpace > 0) {
        truncated = truncated.slice(0, lastSpace);
    }
    return `${truncated.replace(/\s+$/, '')}…`;
}

/**
 * Mechanical PR body: full task, optional Plan from task.md, files-changed
 * block from collectWorktreeChanges, and an orch version footer.
 *
 * @param {{
 *   task: string,
 *   plan?: string|null,
 *   changes: { files: { status: string, path: string }[], shortstat: string }|null|undefined,
 *   slug: string,
 *   agent: string,
 *   version: string,
 * }} opts
 * @returns {string}
 */
export function buildPrBody({ task, plan, changes, slug, agent, version }) {
    const parts = [String(task ?? '').trimEnd(), ''];

    const planText = plan == null ? '' : String(plan).trim();
    if (planText) {
        parts.push('## Plan', '', planText, '');
    }

    parts.push('## Files changed', '', '```text');
    if (changes?.files) {
        for (const { status, path: filePath } of changes.files) {
            parts.push(`  ${status}  ${filePath}`);
        }
    }
    if (changes?.shortstat) {
        parts.push(`  ${changes.shortstat}`);
    }
    parts.push(
        '```',
        '',
        '---',
        `Generated by orch ${version} · run \`${slug}\` · agent \`${agent}\``,
        '',
    );

    return parts.join('\n');
}
